"""
MnMCP v3 - 消息注册表
移植自 MN2MC protobuf_parser.py，包含完整消息码定义

GitHub@StarsailsClover
©BlockConnect Team 2026
"""

from typing import Dict, Optional, Type, Any, Callable
from dataclasses import dataclass
from enum import IntEnum
import logging

logger = logging.getLogger(__name__)


class PacketDirection(IntEnum):
    CLIENT_TO_SERVER = 0
    SERVER_TO_CLIENT = 1
    UNKNOWN = 2


@dataclass
class MessageInfo:
    code: int
    name: str
    direction: PacketDirection
    message_class: Optional[Type] = None
    description: str = ""


class MessageRegistry:
    MSG_CODE_TO_NAME: Dict[int, str] = {
        11: "PB_HeartBeatCH",
        12: "PB_HeartBeatHC",
        101: "PB_SyncChunkDataCH",
        102: "PB_SyncChunkDataHC",
        103: "PB_BlockUpdateCH",
        104: "PB_BlockUpdateHC",
        105: "PB_SyncSectionLightDataHC",
        106: "PB_OverrideLightDataHC",
        1001: "PB_RoleEnterWorldCH",
        1002: "PB_RoleEnterWorldHC",
        1003: "PB_RoleLeaveWorldCH",
        1004: "PB_RoleLeaveWorldHC",
        1006: "PB_ActorEnterAOIHC",
        1008: "PB_ActorLeaveAOIHC",
        1010: "PB_GameLeaderSwitchHC",
        1011: "PB_GeneralEnterAOIHC",
        1012: "PB_PvpActivityConfigCH",
        1013: "PB_RoleCheckJoinFromSrcCH",
        2001: "PB_RoleMoveCH",
        2002: "PB_TrainMoveCH",
        2004: "PB_ActorMoveHC",
        2005: "PB_TrainMoveHC",
        2006: "PB_ActorMoveV2HC",
        2007: "PB_ActorTeleportCH",
        2008: "PB_ActorTeleportHC",
        2009: "PB_ActorMotionHC",
        2010: "PB_MechaMotionHC",
        2011: "PB_GunInfoCH",
        2012: "PB_SetInfoCH",
        2013: "PB_SyncGridUserDataCH",
        2014: "PB_SyncGridUserDataHC",
        2015: "PB_SyncTriggerBlockHC",
        2016: "PB_FullrotActorMoveHC",
        2017: "PB_ActorMotionV2HC",
        2018: "PB_ActorMoveV3HC",
        2019: "PB_ActorModelChangeHC",
        2997: "PB_BlockInteractHC",
        2998: "PB_BlockPunchHC",
        2999: "PB_ItemUseHC",
        3000: "PB_ActorInteractHC",
        3001: "PB_BlockInteractEndCH",
        3002: "PB_BlockInteractCH",
        3003: "PB_BlockPunchCH",
        3004: "PB_ItemUseCH",
        3005: "PB_ActorInteractCH",
        3006: "PB_ActorAnimCH",
        3007: "PB_ActorAnimHC",
        3008: "PB_BackPackGridUpdateHC",
        3009: "PB_BackPackGridSwapCH",
        3010: "PB_BackPackMoveItemCH",
        3011: "PB_BackPackGridDiscardCH",
        3015: "PB_BackPackEquipWeaponCH",
        3016: "PB_BackPackEquipWeaponHC",
        3017: "PB_CloseContainerCH",
        3018: "PB_CloseContainerHC",
        3020: "PB_OpenContainerHC",
        3022: "PB_UpdateContainerHC",
        3023: "PB_SetContainerTextCH",
        3026: "PB_ActorEquipItemHC",
        3029: "PB_BackPackStoreCH",
        3031: "PB_BackPackLootCH",
        3033: "PB_BackPackSortCH",
        3034: "PB_BackPackSetItemCH",
        3035: "PB_StorageBoxSortCH",
        3036: "PB_BackPackShortcutOpCH",
        3037: "PB_CraftItemCH",
        3039: "PB_EnchantItemCH",
        3041: "PB_EnchantItemRandomCH",
        3042: "PB_EnchantItemSuccessHC",
        3043: "PB_RepairItemCH",
        3044: "PB_RepairItemSuccessHC",
        3045: "PB_GunDoReloadCH",
        3046: "PB_GunDoReloadHC",
        3047: "PB_GunRecoveryCH",
        3050: "PB_AccountHorseCH",
        3051: "PB_AccountHorseHC",
        3052: "PB_ActorSetCustomCH",
        3053: "PB_ActorSetCustomHC",
        3054: "PB_ActorPlayAnimCH",
        3055: "PB_ActorPlayAnimHC",
        3056: "PB_ActorAttackCH",
        3057: "PB_ActorDefanceStateCH",
        3058: "PB_RClickUpInteractCH",
        3059: "PB_RClickUpInteractHC",
        3060: "PB_PCMouseEventCH",
        3061: "PB_PlayerGunActionCH",
        3062: "PB_PlayerGunActionStateHC",
        3063: "PB_LivingInteractNewCH",
        3064: "PB_LivingInteractNewNewTameHC",
        3065: "PB_LivingReproductionHC",
        3066: "PB_LivingInteractNewNewGrowHC",
        3067: "PB_TrainFollowOpCH",
        3068: "PB_TrainFollowOpHC",
        4000: "PB_ActorAttrChangeHC",
        4001: "PB_ActorBuffChangeHC",
        4002: "PB_ActorReviveCH",
        4003: "PB_ActorReviveHC",
        4004: "PB_PlayerAttrChangeHC",
        4005: "PB_MobBodyChangeHC",
        4006: "PB_JruisdicTionCH",
        4007: "PB_JruisdicTionHC",
        4010: "PB_ChatCH",
        4011: "PB_ChatHC",
        4012: "PB_WGlobalUpdateHC",
        4013: "PB_PlayersUpdateInfoHC",
        4014: "PB_GameTipsHC",
        4015: "PB_PlayEffectHC",
        4016: "PB_PlayerMountActorCH",
        4017: "PB_PlayerMountActorHC",
        4018: "PB_PlayerMoveInputCH",
        4019: "PB_PlayerRevivePointCH",
        4020: "PB_PlayerSleepHC",
        4021: "PB_PlayerSleepCH",
        4022: "PB_OpenWindowHC",
        4023: "PB_NpcTradeCH",
        4024: "PB_LastPingHC",
        4025: "PB_CGameStageHC",
        4026: "PB_PlayerPermitHC",
        4027: "PB_PlayerRevivePointHC",
        4028: "PB_PlayEffectHC_V2",
        4029: "PB_SkillCDHC",
        4030: "PB_ActorMountActorHC",
        4031: "PB_ActorReverseHC",
        4032: "PB_ActorBindHC",
        4033: "PB_PlayWeaponEffectHC",
        4034: "PB_ScriptVarHC",
        4035: "PB_PlayWeaponEffectCH",
        4037: "PB_SetSpectatorModeCH",
        4038: "PB_SetSpectatorModeHC",
        4039: "PB_SetSpectatorTypeCH",
        4040: "PB_SetSpectatorTypeHC",
        4041: "PB_SetSpectatorPlayerCH",
        4042: "PB_OtherPlayerAttrChangeHC",
        4043: "PB_PlayerLeaveHC",
        4044: "PB_TeamScoreHC",
        4045: "PB_SetTeamHC",
        4046: "PB_SetPlayerGameInfoHC",
        4047: "PB_MoveSyncCH",
        4048: "PB_MoveSyncHC",
        4049: "PB_UIDisplayHorseHC",
        4050: "PB_SyncMoveV2CH",
        4051: "PB_SyncMoveV2HC",
        4052: "PB_UpdateMoveIntervalHC",
        4053: "PB_MoveDiffCH",
        4054: "PB_PlayEffectHC_V3",
        4055: "PB_SyncMoveV4CH",
        4056: "PB_SyncMoveV4HC",
        5001: "PB_ActorGetAccountItem",
        5002: "PB_SpecialItemUseCH",
        5003: "PB_SpecialItemUseHC",
        5004: "PB_LeaveRoomInfoHC",
        5005: "PB_InviteJoinRoomHC",
        5006: "PB_SetSpectatorPlayerHC",
        5007: "PB_SetPlayerModelAniCH",
        5008: "PB_SetPlayerModelAniHC",
        5009: "PB_SendViewmodeSpectatorCH",
        5010: "PB_SendViewmodeSpectatorHC",
        5011: "PB_SetBobbingSpectatorCH",
        5012: "PB_SetBobbingSpectatorHC",
        5013: "PB_ItemSkillUseCH",
        5014: "PB_ItemSkillUseHC",
        5015: "PB_BallOperateCH",
        5016: "PB_BallOperateHC",
        5017: "PB_ResetRoundHC",
        5018: "PB_RocketAttribChangeHC",
        5019: "PB_RocketTeleportCH",
        5020: "PB_SetHookHC",
        5021: "PB_SetHookCH",
        5022: "PB_WorldTimesHC",
        5023: "PB_StatisticHC",
        5024: "PB_TotemPointHC",
        5025: "PB_NeedContainerPasswordHC",
        5026: "PB_NeedContainerPasswordCH",
        5027: "PB_HorseFlyStateHC",
        5028: "PB_OpenDialogueHC",
        5029: "PB_CloseDialogueHC",
        5030: "PB_CloseDialogueCH",
        5031: "PB_AnswerTaskCH",
        5032: "PB_UpdateTaskHC",
        5033: "PB_SyncTaskEnterWorldHC",
        5034: "PB_CompleteTaskHC",
        5035: "PB_CompleteTaskCH",
        5036: "PB_AttractAttribChangeHC",
        5037: "PB_ActorBodyTextureHC",
        5038: "PB_PlayerAddAvartarHC",
        5039: "PB_PlayerChangeModelHC",
        5040: "PB_PlayerAvartarColorHC",
        5041: "PB_PlayActCH",
        5042: "PB_PlayActHC",
        5043: "PB_CreateBlueprintHC",
        5044: "PB_MeasureDistanceHC",
        5045: "PB_BluePrintPreBlockCH",
        5046: "PB_BluePrintPreBlockHC",
        5047: "PB_GravityOperateCH",
        5048: "PB_GravityOperateHC",
        5049: "PB_PlayerBodyColorHC",
        5050: "PB_CustomModelHC",
        5051: "PB_CustomItemIDsHC",
        5052: "PB_PlayerSpawnPointHC",
        5053: "PB_MakeCustomModelCH",
        5054: "PB_SelectMobSpawnerCH",
        5055: "PB_CustomModelClassHC",
        5056: "PB_TransferRecordHC",
        5057: "PB_TransferRecordCH",
        5058: "PB_TransferAddDelHC",
        5059: "PB_TransferStatusCH",
        5060: "PB_TransferStatusHC",
        5061: "PB_SyncLoveAmbassadorIconIdHC",
        5062: "PB_SyncLoveAmbassadorIconIdCH",
        5063: "PB_TransferDataHC",
        5064: "PB_ActorTransferCH",
        5065: "PB_ActorTransferHC",
        5066: "PB_BackPackSetItemWithoutLimitCH",
        5067: "PB_GetNpcShopInfoCH",
        5068: "PB_RespNpcShopInfoHC",
        5069: "PB_BuyNpcShopItemCH",
        5070: "PB_NotifyNpcShopBuySkuHC",
        5071: "PB_VehicleMoveHC",
        5072: "PB_OpenEditActorModelHC",
        5073: "PB_CloseEditActorModelCH",
        5074: "PB_CloseEditActorModelHC",
        5075: "PB_CustomActorModelDataHC",
        5076: "PB_PackGiftNotifyItemChgHC",
        5077: "PB_VehiclePreBlockCH",
        5078: "PB_VehiclePreBlockHC",
        5079: "PB_VehicleItemUseCH",
        5080: "PB_VehicleStartBlockCH",
        5081: "PB_VehicleAllItemIdHC",
        5082: "PB_VehicleOneItemIdHC",
        5083: "PB_VehicleAttribChangeHC",
        5084: "PB_VehicleAttribChangeCH",
        5085: "PB_WorkshopItemInfoCH",
        5086: "PB_WorkshopItemInfoHC",
        5087: "PB_VehicleAssembleBlockUpdateHC",
        5088: "PB_PlayerVehicleMoveInputCH",
        5089: "PB_PlayerResetVehicleCH",
        5090: "PB_PlayerMotionStateChangeCH",
        5091: "PB_PlayerClickCH",
        5092: "PB_PlayerCameraRotateHC",
        5093: "PB_PlayerChangeViewModeHC",
        5094: "PB_PlayerCanMoveHC",
        5095: "PB_PlayerCanControlHC",
        5096: "PB_PlayerSetAttrHC",
        5097: "PB_PlayerFreezingHC",
        5098: "PB_PlayerSelectShortcutCH",
        5099: "PB_GameRuleHC",
        5100: "PB_BasketballOperateHC",
        5101: "PB_BasketballOperateCH",
        5102: "PB_PlayerVehicleMoveInputHC",
        5103: "PB_PlayerCanFireHC",
        5104: "PB_PlayerTouchEvtSyncHC",
        5105: "PB_PlayerTouchEvtCH",
        5200: "PB_BuyAdShopGoods",
        5201: "PB_BuyAdShopGoodsHC",
        5202: "PB_SyncPlayerPosHC",
        5203: "PB_AchievementAwardCH",
        5204: "PB_SyncClientActionLogCH",
        5205: "PB_SyncRoomExtraHC",
        5206: "PB_UploadCheckInfoCH",
        5207: "PB_GetAdShopExtraAwardCH",
        5208: "PB_ExtractStoreItemCH",
        5209: "PB_UploadClientInfoCH",
        5210: "PB_SyncPlayerPosCH",
        6000: "PB_TriggerTimerHC",
        6001: "PB_WorkshopBuildHC",
        6002: "PB_TriggerPlayerAttriCH",
        6003: "PB_PlayerAttrScaleHC",
        6004: "PB_PlayerAttrScaleCH",
        6005: "PB_PlayerNavigateHC",
        6006: "PB_PlayerFaceYawHC",
        6007: "PB_OpenEditFullyCustomModelHC",
        6008: "PB_ReqDownLoadResUrlCH",
        6009: "PB_CloseFullyCustomModelUI_CH",
        6010: "PB_CloseFullyCustomModelUI_HC",
        6011: "PB_RespDownLoadResUrlHC",
        6012: "PB_PreOpenEditFCMUI",
        6013: "PB_EffectScaleHC",
        6014: "PB_PlayerNavFinishedCH",
        6015: "PB_TriggerMusicHC",
        6016: "PB_TriggerSoundCH",
        6017: "PB_PlayerJumpHC",
        6018: "PB_PlayerJumpCH",
        6019: "PB_PlayerSpecialSkillCH",
        6020: "PB_HorseSkillCDHC",
        6021: "PB_CloudServerPermitCH",
        6022: "PB_CloudServerPermitHC",
        6023: "PB_CloudServerAuthorityHC",
        6024: "PB_CloudServerAuthorityCH",
        6025: "PB_SsSyncTaskHC",
        6026: "PB_SsSyncTaskCH",
        6027: "PB_VehicleAssembleBlockAllHC",
        6028: "PB_VehicleAssembleLineCH",
        6029: "PB_VehicleAssembleLineHC",
        6030: "PB_VehicleAssembleLineOperateCH",
        6031: "PB_VehicleAssembleLineOperateHC",
        6032: "PB_UpdateActionerDataCH",
        6033: "PB_VehicleWorkshopLineCH",
        6034: "PB_CloudServerChangeTeamCH",
        6035: "PB_CloudServerChangeStateHC",
        6036: "PB_YMChangeRoleHC",
        6037: "PB_YMChangeRoleCH",
        6038: "PB_YMVoiceCH",
        6039: "PB_YMVoiceHC",
        6040: "PB_CSRentRoomAutoMuteCH",
        6041: "PB_VehicleWorkshopLineUpdateCH",
        6042: "PB_MapEditHandleCH",
        6043: "PB_MapEditRevokeCH",
        6044: "PB_CloudRoomOwnerStartGameCH",
        6045: "PB_CSKickOffDataCH",
        6046: "PB_TriggerOpenStoreHC",
        6047: "PB_UsePackingFCMItemCH",
        6048: "PB_UsePackingFcmItemHC",
        6049: "PB_CreatePackingCMCH",
        6050: "PB_CreatePackingCMHC",
        6051: "PB_PackingFCMDataHC",
        6052: "PB_InputContentCH",
        6053: "PB_InputKeyCH",
        6054: "PB_CloudRoomStatusTimeHC",
        6055: "PB_PlayerVehicleSleepHC",
        6056: "PB_SensorContainerDataCH",
        6057: "PB_SensorContainerDataHC",
        6058: "PB_VehicleBindActorHC",
        6059: "PB_DoorDataHC",
        6060: "PB_PlayerCarryActorCH",
        6061: "PB_PlayerCarryActorHC",
        6062: "PB_VillagerBodyChangeHC",
        6063: "PB_PlayerTameActorHC",
        6064: "PB_VillagerModifyNameCH",
        6065: "PB_VillagerClothHC",
        6066: "PB_ActorHeadDisplayIconHC",
        6067: "PB_ActorPlayAnimByIdHC",
        6068: "PB_VillageTotemTipHC",
        6069: "PB_VillageTotemActiveHC",
        6070: "PB_SaveTombStoneHC",
        6071: "PB_PlayerLevelModeHC",
        6072: "PB_ActionAttrStateHC",
        6073: "PB_EduRoleInfoHC",
        6074: "PB_PlayerGotoPosCH",
        6075: "PB_ImportModelHC",
        6076: "PB_CustomModelPreHC",
        6077: "PB_CustomModelPreCH",
        6078: "PB_PlayerResetDeformationCH",
        6079: "PB_PlayerDeformationSkinCH",
        6080: "PB_PlayerTransformSkinHC",
        6081: "PB_PlayerRestoreTransformSkinCH",
        6082: "PB_PlayerSaveArchHC",
        6083: "PB_PlayerPushArchCH",
        6084: "PB_LightningHC",
        6085: "PB_InteractMobPackHC",
        6086: "PB_UpdateMobBackpackHC",
        6087: "PB_MoveMobBackpackItemCH",
        6088: "PB_InteractMobBackpackItemCH",
        6089: "PB_AltarLuckyDrawCH",
        6090: "PB_SFActivityHC",
        6091: "PB_OpenDevGoodsBuyDialogHC",
        6092: "PB_HomePrayInfoHC",
        6093: "PB_HomePrayTreeStateHC",
        6094: "PB_HomePrayReqHC",
        6095: "PB_PrayTreeTimeCH",
        6096: "PB_PrayTreeTimeUpdateHC",
        6097: "PB_PrayErrorHC",
        6098: "PB_HomeNpcOpenHC",
        6099: "PB_OpenHomeClosetHC",
        6100: "PB_GodTempleCreateHC",
        6101: "PB_ShapeAdditionAnimHC",
        6102: "PB_SummonPetCH",
        6103: "PB_HomelandRanchInfoHC",
        6104: "PB_HomeLandRanchUpdateAnimalStateCH",
        6105: "PB_PlayGraphicsHC",
        6106: "PB_UseItemByHomelandHC",
        6107: "PB_CustomBaseModelHC",
        6108: "PB_ChangeActorModelHC",
        6109: "PB_RequestModelName",
        6110: "PB_NotifiyActorModelHC",
        6111: "PB_VoiceInformCH",
        6112: "PB_VoiceInformHC",
        6113: "PB_RuneOperateCH",
        6114: "PB_RuneOperateSuccessHC",
        6115: "PB_FurnaceTemperatureCH",
        6116: "PB_PlayerTakeContainerGridItemCH",
        6117: "PB_PlayerPotSetMakeCH",
        6118: "PB_UpdatePotContainerHC",
        6119: "PB_NotifyStarStationAddedHC",
        6120: "PB_NotifyStarStationRemovedHC",
        6121: "PB_NotifyStarStationChangeNameStatusHC",
        6122: "PB_StarStationChangeNameStatusCH",
        6123: "PB_NotifyEnterStarStationCabinHC",
        6124: "PB_LeaveStarStationCabinCH",
        6125: "PB_NotifyLeaveStarStationCabinHC",
        6126: "PB_UpdateStarStationCabinLevelCH",
        6127: "PB_NotifyUpdateStarStationCabinLevelHC",
        6128: "PB_UpdateStarStationCabinStatusCH",
        6129: "PB_NotifyUpdateStarStationCabinStatusHC",
        6130: "PB_NotifyUpdateStarStationCabinAddedHC",
        6131: "PB_NotifyUpdateStarStationCabinRemovedHC",
        6132: "PB_AddUnfinishedTransferRecordCH",
        6133: "PB_NotifyAddUnfinishedTransferRecordHC",
        6134: "PB_NotifyUpdateUnfinishedTransferRecordStatusHC",
        6135: "PB_RemoveUnfinishedTransferRecordCH",
        6136: "PB_NotifyRemoveUnfinishedTransferRecordHC",
        6137: "PB_StarStationDataHC",
        6138: "PB_PlayerTransferByStarStationCH",
        6139: "PB_NotifyPlayerTransferByStarStationHC",
        6140: "PB_NotifyActivateStarStationHC",
        6141: "PB_NotifyUpgradeStarStationCabinHC",
        6142: "PB_NotifyUpdateStarStationSignInfoHC",
        6143: "PB_RequireStarStationTransferCH",
        6144: "PB_NotifyStarStationTransferResultHC",
        6145: "PB_BlockExploitCH",
        6146: "PB_BlockExploitHC",
        6147: "PB_VacantBossStateHC",
        6148: "PB_BackPackRemoveItemItemCH",
        6149: "PB_PlayAltmanMusicHC",
        6150: "PB_NotifyUpdateToolModelTextureHC",
        6151: "PB_GainItemsToBackPackCH",
        6152: "PB_UpdateStarStationCabinStatusEndCH",
        6153: "PB_NotifyUpdateStarStationCabinStatusEndHC",
        6154: "PB_AddStarStationTransferDescCH",
        6155: "PB_AddExpCH",
        6156: "PB_AddExpResultHC",
        6157: "PB_CoustomUIEvent",
        6158: "PB_AchievementSyncHC",
        6159: "PB_AchievementUpdateCH",
        6160: "PB_BPEventHC",
        6161: "PB_AddStarCH",
        6162: "PB_UseHearthCH",
        6163: "PB_ActorStopAnimHC",
        6164: "PB_ActorStopAnimCH",
        6167: "PB_HomeLandRanchFooderCH",
        6168: "PB_HorseFlagHC",
        6169: "PB_HomeLandRanchFooderStateHC",
        6170: "PB_AchievementInitDataHC",
        6171: "PB_HomeLandMenuBuyHC",
        6172: "PB_HomeLandMenuBuyCH",
        6173: "PB_HomeLandFarmShopHC",
        6174: "PB_HomeLandFarmShopCH",
        6177: "PB_HomeLandSpecialFurnitureBuyHC",
        6178: "PB_HomeLandSpecialFurnitureBuyCH",
        6179: "PB_PlayerOpenUIHC",
        6180: "PB_AnswerLanternBird_CH",
        6181: "PB_ExchangeItemsToBackPackCH",
        6182: "PB_ExchangeItemsToBackPackResultHC",
        6183: "PB_ChangeQQMusicPlayerHC",
        6184: "PB_ChangeQQMusicPlayerCH",
        6185: "PB_SetTiangouHC",
        6186: "PB_PlayeCloseUICH",
        6187: "PB_RideInvisibleHC",
        6188: "PB_ActorPlaySoundCH",
        6189: "PB_ActorInviteCH",
        6190: "PB_ActorInviteHC",
        6191: "PB_PlaySkinActHC",
        6192: "PB_PlaySkinActCH",
        6193: "PB_ChangeQQMusicClubHC",
        6194: "PB_ChangeQQMusicClubCH",
        6195: "PB_ActorStopSkinActHC",
        6196: "PB_MiniClubMusicPlayerHC",
        6197: "PB_MiniClubMusicPlayerCH",
        6198: "PB_ActorStopSkinActCH",
        6199: "PB_SprayPaintInfoCH",
        6200: "PB_AddPaintedInfoHC",
        6201: "PB_RemovePaintedInfoHC",
        6202: "PB_EquipWeaponHC",
        6203: "PB_EquipWeaponCH",
        6204: "PB_PlayEffectCH",
        6205: "PB_GainItemsUserDatastrToBackPackCH",
        6206: "PB_UseMusicYuPuCH",
        6207: "PB_DanceByPlayingCH",
        6208: "PB_StopDanceByPlayingCH",
        6209: "PB_StartActCH",
        6210: "PB_StopActCH",
        6211: "PB_TopBrandCH",
        6212: "PB_TopBrandHC",
        6213: "PB_HostCheckCheat",
        6214: "PB_WeaponPointHC",
        6215: "PB_GameModeChangeHC",
        6216: "PB_AddLightningChainHC",
        6217: "PB_STARTFISHINGCH",
        6218: "PB_STARTFISHINGHC",
        6219: "PB_ENDFISHINGCH",
        6220: "PB_ENDFISHINGHC",
        6221: "PB_QUITFISHINGCH",
        6222: "PB_QUITFISHINGHC",
        6223: "PB_CHANGEFISHINGSTAGEHC",
        6224: "PB_ExposePosChangeCH",
        6225: "PB_NotifyUpdateToolModelTextureCH",
        6226: "PB_BindItemToActorHC",
        6227: "PB_FishingBeginFlashHC",
        6228: "PB_EndPlayFishCH",
        6229: "PB_ChangeShowEquipHC",
        6240: "PB_ResetRoleFlagsHC",
        6241: "PB_BindPlayerToPhysicsPlatHC",
        6242: "PB_UnbindPlayerToPhysicsPlatHC",
        6243: "PB_PhysicsComUpdate",
        6244: "PB_PhysicsComPlatLocalPos",
        6245: "PB_EffectComParticleUpdate",
        6246: "PB_SoundComUpdate",
        6247: "PB_BindPlayerToPhysicsPlatCH",
        6248: "PB_UnbindPlayerToPhysicsPlatCH",
        6249: "PB_MeteorShowerHC",
        6250: "PB_PlayerTransferHC",
        6251: "PB_NotifyPlayerBlockChangeColorAnimHC",
        6252: "PB_ActorPlayHandAnimHC",
        6253: "PB_BlockPlayAnimHC",
        6254: "PB_BlockStructUpdateHC",
        6255: "PB_PlayerEnterLivingwheelHC",
        6256: "PB_PlayerLeaveLivingwheelHC",
        6257: "PB_PlayerWorkingLivingwheelCH",
        6258: "PB_UpdateLivingwheelHC",
        6259: "PB_RequestLivingwheelCH",
        6260: "PB_CreateBlockCH",
        6261: "PB_ActorVillagerInfoHC",
        6262: "PB_ActorSandwormShowHC",
        6263: "PB_ActorSandwormCanMoveHC",
        6264: "PB_ActorScaleHC",
        6265: "PB_ActorSandwormNibblePlayerHC",
        6266: "PB_ActorCreateThornballHC",
        6267: "PB_ActorReboundsAttackUpHC",
        6268: "PB_ActorReboundsAttackRoundHC",
        6269: "PB_RemoveSawtoothThornbHC",
        6270: "PB_ChNoticeAttackedUpCH",
        6271: "PB_ChNoticeAttackedRoundCH",
        6272: "PB_ChNoticeRemoveSawtoothThornbaCH",
        6273: "PB_AttrShapeShiftRightClickCH",
        6274: "PB_DestoryBlockCH",
        6275: "PB_WaterPressureCH",
        6276: "PB_AttrShapeShiftSyncHC",
        6277: "PB_CoconutHitHC",
        6278: "PB_CoconutSkipNightHC",
        6279: "PB_ActorSharkBitePlayerMoveHC",
        6280: "PB_CrabInfoSyncHC",
        6281: "PB_CrabClickCountResetCH",
        6282: "PB_HippocampusRefreshModelHC",
        6283: "PB_HippocampusChangeColorHC",
        6284: "PB_BackpackGridDurationHC",
        6285: "PB_GunLogicUseWaterCanoonSkillCH",
        6286: "PB_ActorSnowmanPartShowHC",
        6287: "PB_MobPartShowHC",
        6288: "PB_PlayerShakeCH",
        6289: "PB_ActorDissolveComponentOpenHC",
        6290: "PB_CookBookInfoHC",
        6291: "PB_StoveTakeCH",
        6292: "PB_SetHpVisibleHC",
        6293: "PB_SkillplayanimHC",
        6294: "PB_SkillstopanimHC",
        6295: "PB_SkillplaybodyeffectHC",
        6296: "PB_SkillstopbodyeffectHC",
        6297: "PB_SkillworldplaybodyeffectHC",
        6298: "PB_AccumulatorHC",
        6299: "PB_SkillplaytoolanimHC",
        6300: "PB_SkillstoptoolanimHC",
        6301: "PB_SkillsetchargemoveHC",
        6302: "PB_SkillmoveHC",
        6303: "PB_SkillcameraHC",
        6304: "PB_StopweaponanimHC",
        6305: "PB_StopweaponanimCH",
        6306: "PB_StopweaponmotionHC",
        6307: "PB_StopweaponmotionCH",
        6308: "PB_SetlocotypeHC",
        6309: "PB_BasestateHC",
        6310: "PB_SetmovementModeHC",
        6311: "PB_HorseflystateHC",
        6312: "PB_PlayerCameraconfigHC",
        6313: "PB_BackpackNumChangeHC",
        6314: "PB_PlaySkinVoiceCH",
        6315: "PB_PlaySkinVoiceHC",
        6316: "PB_BoxPlayAniCH",
        6317: "PB_NewYearBossStageHC",
        6318: "PB_NewYearHpHC",
        6320: "PB_NewYearMonsterPosHC",
        6321: "PB_StorageBoxPutAllCH",
        6322: "PB_TeleportShowPanelHC",
        6323: "PB_DynamicProtoHC",
        6324: "PB_DynamicProtoCH",
        6330: "PB_StorageBoxTakeOutAllCH",
        6331: "PB_SyncDyeableItemCH",
        6332: "PB_CustomPbcCH",
        6333: "PB_CustomPbcHC",
        6334: "PB_UpdateLaserPointerHC",
        6335: "PB_UpdateLaserPointerCH",
        6500: "PB_PhysicsInputFrame",
        6501: "PB_PhysicsTimestamp",
        6502: "PB_PhysicsSetupTimestamp",
        6503: "PB_PhysicsTimeDilation",
        6504: "PB_PhysicsReplicatedInputCH",
        6505: "PB_PhysicsReplicatedInputHC",
        6506: "PB_PhysicsReplicatedStateCH",
        6507: "PB_PhysicsReplicatedStateHC",
        6508: "PB_PhysicsCommonReplicated",
        7000: "PB_CustomMsg",
        7001: "PB_BlockDataCH",
        7002: "PB_PushSnowBallOperateCH",
        7003: "PB_PushSnowBallOperateHC",
        7004: "PB_PushSnowBallSizeChangeHC",
        7005: "PB_PlayEffectShaderHC",
        7006: "PB_NewRepairItemCH",
        7007: "PB_SendObjActorMsg",
        7008: "PB_AddBulletholeHC",
        7009: "PB_ActorShootCH",
        7010: "PB_ActorFireworkCH",
        7011: "PB_ActorPlayAnimNewCH",
        7012: "PB_ActorSpeedChangeHC",
        7013: "PB_TaskInitDataHC",
        7014: "PB_ByMountHC",
        7016: "PB_ActorPickupActorHC",
        7018: "PB_ActorDropActorHC",
        7019: "PB_WeatherHC",
        7020: "PB_ByMountCH",
        7021: "PB_AddBulletholeV2HC",
        7024: "PB_ActorSetAttrToTrackingPlayersHC",
        7025: "PB_TaskObjectiveInitDataHC",
        7026: "PB_PlayWeaponMotionHC",
        7027: "PB_PlayWeaponMotionCH",
        7028: "PB_PlayWeaponAnimHC",
        7029: "PB_PlayWeaponAnimCH",
        7030: "PB_ActorJumpHC",
        7031: "PB_TechTreeInfoChangeHC",
        7032: "PB_SetGravityFailureHC",
        7033: "PB_SetInteractActorMechaHC",
        7034: "PB_UnlockItemsHC",
        7035: "PB_CheckNewUnlockItem_CH",
        7036: "PB_PlayCameraShakeHC",
        7037: "PB_RecentlyMakeCraft_CH",
        7038: "PB_MechaKineticUintHC",
        7039: "PB_KineticNodeDataHC",
        7040: "PB_ContainerUIData_HC",
        7041: "PB_ContainerUIData_CH",
        7042: "PB_MechaRecoveryHeadHC",
        7043: "PB_MechaTunnelAnimPlayHC",
        7044: "PB_MechaStructureSyncHC",
        7045: "PB_MechaStructureOperateCH",
        7046: "PB_MechaStructureOperateHC",
        7047: "PB_TransferGoodsCompHC",
        7048: "PB_PickTransferGoodItem_CH",
        7049: "PB_MechaKineticNodeLogicDataHC",
        7050: "PB_MechaAddKineticNodeLogicHC",
        7051: "PB_IronDomeEssenceDisEquip_CH",
        7052: "PB_IronHC",
        7053: "PB_IronDomeEssenceEquip_HC",
        7054: "PB_Part_HC",
        7055: "PB_PartManager_HC",
        7056: "PB_BlockTextureColors_HC",
        7057: "PB_LookAtActorHC",
        7058: "PB_SandboxLuaLogDataCH",
        7059: "PB_SandboxLuaLogDataHC",
        7101: "PB_AI_TTS_AUDIO_HC_MSG",
        7102: "PB_AI_ASR_AUDIO_CH_MSG",
        7103: "PB_ModContainer_HC",
        7104: "PB_WBPMsgHC",
        7105: "PB_WBPMsgCH",
        7106: "PB_RakePlantItemId_CH",
        7107: "PB_AvatarPartsPrioritySyncHC",
        7108: "PB_AvatarPartsPrioritySyncAllHC",
        7109: "PB_ActorChatBubbleHC",
        7110: "PB_SleepMsgHC",
        7111: "PB_DropItemStateData_HC",
        7112: "PB_DropItemInteractResult_CH",
        7113: "PB_ActorSwitchPhysicTypeHC",
        7114: "PB_PlayerUseItem_CH",
        7115: "PB_PlayerPlayHandAnim_HC",
        7116: "PB_PlayerPlayDigBlockEffect_HC",
        7117: "PB_ActorPlayAnimFinishCH",
        10002: "PB_WorldSyncSaveHC",
    }

    MSG_DIRECTION: Dict[int, PacketDirection] = {}
    _message_classes: Dict[int, Type] = {}
    
    def __init__(self):
        self._build_direction_map()
    
    def _build_direction_map(self) -> None:
        for code, name in self.MSG_CODE_TO_NAME.items():
            if name.endswith("CH"):
                self.MSG_DIRECTION[code] = PacketDirection.CLIENT_TO_SERVER
            elif name.endswith("HC"):
                self.MSG_DIRECTION[code] = PacketDirection.SERVER_TO_CLIENT
            else:
                self.MSG_DIRECTION[code] = PacketDirection.UNKNOWN
    
    def get_name(self, code: int) -> Optional[str]:
        return self.MSG_CODE_TO_NAME.get(code)
    
    def get_code(self, name: str) -> Optional[int]:
        for code, msg_name in self.MSG_CODE_TO_NAME.items():
            if msg_name == name:
                return code
        return None
    
    def get_direction(self, code: int) -> PacketDirection:
        return self.MSG_DIRECTION.get(code, PacketDirection.UNKNOWN)
    
    def register_class(self, code: int, message_class: Type) -> None:
        self._message_classes[code] = message_class
        logger.debug(f"Registered message class: {code} -> {message_class.__name__}")
    
    def get_message_class(self, code: int) -> Optional[Type]:
        return self._message_classes.get(code)
    
    def is_client_to_server(self, code: int) -> bool:
        return self.get_direction(code) == PacketDirection.CLIENT_TO_SERVER
    
    def is_server_to_client(self, code: int) -> bool:
        return self.get_direction(code) == PacketDirection.SERVER_TO_CLIENT
    
    def get_all_codes(self) -> list:
        return list(self.MSG_CODE_TO_NAME.keys())
    
    def get_stats(self) -> Dict[str, int]:
        total = len(self.MSG_CODE_TO_NAME)
        ch_count = sum(1 for d in self.MSG_DIRECTION.values() if d == PacketDirection.CLIENT_TO_SERVER)
        hc_count = sum(1 for d in self.MSG_DIRECTION.values() if d == PacketDirection.SERVER_TO_CLIENT)
        registered = len(self._message_classes)
        
        return {
            'total_messages': total,
            'client_to_server': ch_count,
            'server_to_client': hc_count,
            'classes_registered': registered,
        }


_registry = MessageRegistry()


def get_message_name(code: int) -> Optional[str]:
    return _registry.get_name(code)


def get_message_direction(code: int) -> PacketDirection:
    return _registry.get_direction(code)


def get_message_class(code: int) -> Optional[Type]:
    return _registry.get_message_class(code)


def register_message_class(code: int, message_class: Type) -> None:
    _registry.register_class(code, message_class)


if __name__ == "__main__":
    registry = MessageRegistry()
    
    print("=" * 60)
    print("MnMCP v3 - 消息注册表测试")
    print("=" * 60)
    
    test_codes = [11, 1001, 2001, 3002, 4010, 5001, 6001, 7000, 10002]
    
    print("\n消息查询测试:")
    for code in test_codes:
        name = registry.get_name(code)
        direction = registry.get_direction(code)
        dir_str = "CH" if direction == PacketDirection.CLIENT_TO_SERVER else "HC" if direction == PacketDirection.SERVER_TO_CLIENT else "?"
        print(f"  {code:5d} -> {name:45s} ({dir_str})")
    
    stats = registry.get_stats()
    print(f"\n统计信息:")
    print(f"  总消息数: {stats['total_messages']}")
    print(f"  Client->Server: {stats['client_to_server']}")
    print(f"  Server->Client: {stats['server_to_client']}")
    print(f"  已注册类: {stats['classes_registered']}")
    
    print("\n✓ 消息注册表测试通过")